name: libcalendar
description: Calendar Conversion Library for Dart.
version: 0.2.0
author: Zulfahmi Ahmad <zulfahmi93@outlook.com>
homepage: https://github.com/zulfahmi93/dart_libcalendar

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  logging: ^1.0.1
  meta: ^1.3.0

dev_dependencies:
  test: ^1.16.8
